# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_remove_gradetype_language_exam_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='decree',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='gradetype',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='language',
            name='uuid',
        ),
    ]
