# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-14 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_auto_20180727_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='decree',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='gradetype',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='language',
            name='uuid',
        ),
    ]
