# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0021_remove_attribution_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='uuid',
        ),
    ]
