# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20180606_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendar',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='entitycomponentyear',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='entitycontaineryear',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='entityversion',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='externaloffer',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='learningcomponentyear',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='learningcontainer',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='learningunit',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='learningunitcomponent',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='learningunitenrollment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='offerenrollment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='offeryeardomain',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='uuid',
        ),
    ]
